<a href="https://colab.research.google.com/github/polvaishnavi1782-hash/T170800237_TNSF_AIML/blob/main/Day_4_Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1,2,3,4,5,6]) # 1D
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((5,3))  #3R / 4C
ones = np.ones((2,3))
identity = np.eye(6)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(1, 46, 5)
linspace_arr = np.linspace(1, 10, 10)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(4,5)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)

1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Arange: [ 1  6 11 16 21 26 31 36 41]
Linspace: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Random Array:
 [[0.4100702  0.54828922 0.31073222 0.64901928 0.2434998 ]
 [0.12298389 0.62323962 0.35263456 0.89100983 0.31292029]
 [0.30921855 0.9167655  0.70607069 0.4406722  0.06790984]
 [0.15437412 0.74063038 0.59343619 0.99845103 0.13898518]]
Random Array:
 [[410070 548289 310732 649019 243499]
 [122983 623239 352634 891009 312920]
 [309218 916765 706070 440672  67909]
 [154374 740630 593436 998451 138985]]


In [ ]:
# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr + 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [15 25 35 45]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]


In [ ]:
from typing_extensions import dataclass_transform
# Importing Pandas
import pandas as pd

# Creating a Series
data = [10, 20, 30,40, 40]
print(data)
series = pd.Series(data, index=[1001,1002,1003,'disha','bharti'])
print("Series:\n", series)

# Creating a DataFrame
data_dict = {
    'Name': ['Alice', 'Shraddha','Bob', 'Charlie', 'David','pooja','pooja','Harshali','jyoti'],
    'Age': [24,34, 25, 22,4,17,15,20,20],
    'City': ['New York', 'New Delhi','New Jersey', 'London', 'Tokyo','Mumbai','Chicago','Washington','Washington']

}
print(data_dict)
df = pd.DataFrame(data_dict)
print("\nDataFrame:\n", df)

# Reading CSV file (example)
#df = pd.read_csv("data.csv")

# Basic DataFrame info
print("\nHead:\n", df.head())
print("\nInfo:\n")
print(df.info())
print("\nDescribe:\n", df.describe())

[10, 20, 30, 40, 40]
Series:
 1001      10
1002      20
1003      30
disha     40
bharti    40
dtype: int64
{'Name': ['Alice', 'Shraddha', 'Bob', 'Charlie', 'David', 'pooja', 'pooja', 'Harshali', 'jyoti'], 'Age': [24, 34, 25, 22, 4, 17, 15, 20, 20], 'City': ['New York', 'New Delhi', 'New Jersey', 'London', 'Tokyo', 'Mumbai', 'Chicago', 'Washington', 'Washington']}

DataFrame:
        Name  Age        City
0     Alice   24    New York
1  Shraddha   34   New Delhi
2       Bob   25  New Jersey
3   Charlie   22      London
4     David    4       Tokyo
5     pooja   17      Mumbai
6     pooja   15     Chicago
7  Harshali   20  Washington
8     jyoti   20  Washington

Head:
        Name  Age        City
0     Alice   24    New York
1  Shraddha   34   New Delhi
2       Bob   25  New Jersey
3   Charlie   22      London
4     David    4       Tokyo

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
--- 

In [ ]:
# Example 1: Selecting columns and rows
print("Single Column:\n", df['Name'])
print("\nMultiple Columns:\n", df[['Name', 'Age']])
print("\nRow by index (iloc):\n", df.iloc[1])
print("\nRow by label (loc):\n", df.loc[1])

# Example 2: Filtering data
print("\nPeople older than 18:\n", df[df['Age'] > 18])

# Example 3: Adding a new column
df['Salary'] = [50000, 60000, 55000, 70000,45000,90000,100000,10000,20000]
print("\nWith Salary Column:\n", df)

# Example 4: Handling missing data
df2 = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, None, 8]
})
print("\nOriginal with NaN:\n", df2)
print("\nDrop NaN:\n", df2.dropna())
print("\nFill NaN with 0:\n", df2.fillna(2.0))

# Example 5: GroupBy and Aggregation
grouped = df.groupby('City')['Salary'].mean()
print("\nAverage Salary by City:\n", grouped)

# Example 6: Sorting
print("\nSorted by Age:\n", df.sort_values(by='Age'))

# Example 7: Merging DataFrames
df_extra = pd.DataFrame({
    'Name': ['pooja', 'shraddha'],
    'Department': ['HR', 'IT']
})
merged = pd.merge(df, df_extra, on='Name', how='outer')
print("\nMerged DataFrame:\n", merged)


Single Column:
 0       Alice
1    Shraddha
2         Bob
3     Charlie
4       David
5       pooja
6       pooja
7    Harshali
8       jyoti
Name: Name, dtype: object

Multiple Columns:
        Name  Age
0     Alice   24
1  Shraddha   34
2       Bob   25
3   Charlie   22
4     David    4
5     pooja   17
6     pooja   15
7  Harshali   20
8     jyoti   20

Row by index (iloc):
 Name     Shraddha
Age            34
City    New Delhi
Name: 1, dtype: object

Row by label (loc):
 Name     Shraddha
Age            34
City    New Delhi
Name: 1, dtype: object

People older than 18:
        Name  Age        City
0     Alice   24    New York
1  Shraddha   34   New Delhi
2       Bob   25  New Jersey
3   Charlie   22      London
7  Harshali   20  Washington
8     jyoti   20  Washington

With Salary Column:
        Name  Age        City  Salary
0     Alice   24    New York   50000
1  Shraddha   34   New Delhi   60000
2       Bob   25  New Jersey   55000
3   Charlie   22      London   70000
4     Dav